rules:
  indent:
    - 2
    - tab
  quotes:
    - 2
    - single
  linebreak-style:
    - 2
    - unix
  semi:
    - 2
    - never
  no-console:
    - 2
    - false
env:
  es6: true
  node: true
extends: 'eslint:recommended'
